<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Categories' => 'Kategorie',
  'Exceptions' => 'Wyjątki',
  'Failed to save category {category} for subscription {subscription_id}' => 'Nie udało się zapisać kategorii {category} dla subskrypcji {subscription_id}',
  'Failed to save message \'{msg}\' in queue {queue_name}.' => 'Nie udało się zapisać wiadomości \'{msg}\' w kolejce {queue_name}.',
  'Failed to save message \'{msg}\' in queue {queue_name} for the subscription {subscription_id}.' => 'Nie udało się zapisać wiadomości \'{msg}\' w kolejce {queue_name} dla subskrypcji {subscription_id}.',
  'Failed to subscribe {subscriber_id} to {queue_name}' => 'Nie udało się zapisać {subscriber_id} do kolejki {queue_name}',
  'Label' => 'Etykieta',
  'Message {id}' => 'Wiadomość {id}',
  'Not sending message \'{msg}\' to queue {queue_name}.' => 'Nie wysyłam wiadomości \'{msg}\' do kolejki {queue_name}.',
  'Queue {queue_name} is full.' => 'Kolejka {queue_name} jest pełna.',
  'Queue id must be exactly a one character.' => 'Id kolejki to musi być dokładnie jeden znak.',
  'Queue with given ID was not found.' => 'Kolejka o podanym ID nie została odnaleziona.',
  'Message with given ID was not found.' => 'Wiadomość o podanym ID nie została odnaleziona.',
  'Sent message \'{msg}\' to queue {queue_name}.' => 'Wysłano wiadomość \'{msg}\' do kolejki {queue_name}.',
  'Subscribe' => 'Zapisz się',
  'Unsubscribe' => 'Wypisz się',
  'Back to messages list' => 'Wróć do listy wiadomości',
  'List' => 'Lista',
  'Mark all as read' => 'Oznacz wszystkie jako przeczytane',
  'Mark as read' => 'Oznacz jako przeczytaną',
  'Message category' => 'Kategoria wiadomości',
  'Message content' => 'Treść wiadomości',
  'Newer' => 'Nowsze',
  'No message body' => 'Brak treści wiadomości',
  'Older' => 'Starsze',
  'Other recipients' => 'Pozostali odbiorcy',
  'Queues' => 'Kolejki',
  'Submit' => 'Wyślij',
  'Subscriptions' => 'Subskrypcje',
  'View all messages' => 'Zobacz wszystkie wiadomości',
  'View messages' => 'Zobacz wiadomości',
);
